################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/SIGMA_ECC.c \
../Core/Src/SIGMA_flash_if.c \
../Core/Src/SIGMA_lzss_aes_gcm.c \
../Core/Src/SIGMA_main.c \
../Core/Src/stm32f4xx_hal_msp.c \
../Core/Src/stm32f4xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32f4xx.c 

OBJS += \
./Core/Src/SIGMA_ECC.o \
./Core/Src/SIGMA_flash_if.o \
./Core/Src/SIGMA_lzss_aes_gcm.o \
./Core/Src/SIGMA_main.o \
./Core/Src/stm32f4xx_hal_msp.o \
./Core/Src/stm32f4xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32f4xx.o 

C_DEPS += \
./Core/Src/SIGMA_ECC.d \
./Core/Src/SIGMA_flash_if.d \
./Core/Src/SIGMA_lzss_aes_gcm.d \
./Core/Src/SIGMA_main.d \
./Core/Src/stm32f4xx_hal_msp.d \
./Core/Src/stm32f4xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32f4xx.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/SIGMA_ECC.o: ../Core/Src/SIGMA_ECC.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/SIGMA_ECC.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/SIGMA_flash_if.o: ../Core/Src/SIGMA_flash_if.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/SIGMA_flash_if.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/SIGMA_lzss_aes_gcm.o: ../Core/Src/SIGMA_lzss_aes_gcm.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/SIGMA_lzss_aes_gcm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/SIGMA_main.o: ../Core/Src/SIGMA_main.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/SIGMA_main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f4xx_hal_msp.o: ../Core/Src/stm32f4xx_hal_msp.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f4xx_it.o: ../Core/Src/stm32f4xx_it.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32f4xx.o: ../Core/Src/system_stm32f4xx.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/ecc" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/hash" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/legacy_v3/src/cipher" -I"C:/Users/HP/Documents/work_space/Embedded_Secure_Encryp_Comp/Bootloader/STM32_Cryptographic/include/cipher" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

