/*
 * uECC.h
 *
 * @brief   ECDSA P-256 signature verification for STM32 bootloader.
 * @author  SAID ARNOUZ
 * @date    2026
 *
 * Created on: Mar 5, 2026
 */

#ifndef INC_UECC_H_
#define INC_UECC_H_

#include "string.h"
#include "stm32f4xx_hal.h"
#include "cmox_crypto.h"

/* CMOX direct API — no legacy wrapper needed */
#include "cmox_crypto.h"
#include "hash/cmox_sha256.h"
#include "ecc/cmox_ecdsa.h"
#include "ecc/cmox_ecc.h"

/* ECDSA P-256 raw signature size: R || S, 32 bytes each */
#define SIG_SIZE                64U

/* Working memory for CMOX ECC operations, 1KB sufficient for P-256 verify */
#define CMOX_ECC_MEMBUF_SIZE    1024U

/*
 * ECDSA P-256 public key.
 * Generated by keygen (flash_app_uart.py).
 * Replace when a new keypair is generated.
 * Format: uncompressed X || Y, 32 bytes each, big-endian, total 64 bytes.
 */
static const uint8_t PUBLIC_KEY[64] = {
    0x38, 0x1F, 0x17, 0x46, 0x30, 0x89, 0x26, 0xC2,
    0xA6, 0xF4, 0xD4, 0xDE, 0xB4, 0xB5, 0x10, 0x1B,
    0xF7, 0x60, 0x40, 0x66, 0x8D, 0x30, 0x12, 0x4C,
    0x92, 0xFA, 0xD4, 0x8C, 0xB1, 0x50, 0xC8, 0xAA,
    0x80, 0xEA, 0xE0, 0x78, 0x0B, 0x47, 0xAD, 0x2E,
    0x3F, 0x56, 0xE4, 0xC4, 0x31, 0x4E, 0x03, 0xB7,
    0x35, 0xA6, 0xA1, 0x5C, 0x4A, 0x27, 0x3B, 0x2E,
    0x8F, 0x7C, 0x74, 0x96, 0x1E, 0x8D, 0xAA, 0x34,
};

/**
 * @brief   Verifies the ECDSA P-256 signature of the application firmware.
 * @param   app_address : start address of the application in flash.
 * @param   app_size    : size of the application in bytes.
 * @param   signature   : pointer to the raw signature R || S (64 bytes).
 * @return  1 : signature valid.
 *          0 : signature invalid or verification error.
 */
uint8_t Boot_VerifySignature(uint32_t app_address, uint32_t app_size, const uint8_t *signature);

#endif /* INC_UECC_H_ */
